sudo: required

language: cpp

branches:
  only:
  - master
  - experimental

services:
  - docker

env:
  - BRANCH=stable
  - BRANCH=master

cache:
  directories:
    - ~/.re-docker

install:
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

before_script:
  - docker login -u=iceflower -p="$DOCKER_PASSWORD"
  - mkdir -p ~/.re-docker/sha/re/
  - mkdir -p ~/.re-docker/sha/baseImg/
  - mkdir -p ~/.re-docker/sha/dockerfile/

script:
  - bash scripts/update.sh
