sudo: required

services:
  - docker

install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
# build amd64 docker
#  - export TAG=`if [ "$TRAVIS_BRANCH" != "" ]; then echo "latest"; else echo $TRAVIS_TAG ; fi`
  - export TAG=latest
  - export REPO=iceflower/red-eclipse_devel_server_test
  - docker build -t $REPO ./amd64/
  - docker tag $REPO $TAG

after_success:
  - docker login -u=iceflower -p="$DOCKER_PASSWORD"
  - docker push $REPO
