sudo: required

language: cpp

services:
  - docker

env:
  - BRANCH="stable"
  - BRANCH="master"

cache:
  directories:
    - ./sha

install:
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

before_script:
  - docker login -u=iceflower -p="$DOCKER_PASSWORD"
  - mkdir -p ./sha/re/
  - mkdir -p ./sha/docker/

script:
  - bash scripts/update.sh
