language: go
go:
  - "1.13"
os: linux
dist: bionic

addons:
  apt:
    update: true
    packages:
      - docker-ce

services:
  - docker

branches:
  only:
    - master
    - experimental

env:
  global:
    - REPO=iceflower/redeclipse-server
    - USER=iceflower
    - ARCH=amd64

jobs:
  include:
    - stage: "build"
      name: "updater"
      before_script:
        - mkdir -p ~/aws-cache/
      script:
        - cd go-github-webhook
        - go build -x -o updater ./cmd/updater/
        - cp ./updater ~/aws-cache/
      after_script: skip
      after_success:
        - aws s3 sync s3://iceflower-redeclipse-server-docker/$TRAVIS_BUILD_NUMBER ~/aws-cache/
    -
      script:
        - cd go-github-webhook
        - go build -x -o server ./cmd/server/
      name: "server"
      before_script: skip
      after_script: skip
    - stage: "update"
      name: "refs/heads/master"
      env:
        - DOCKERFILE=Dockerfile_master
    -
      name: "refs/heads/stable"
      env:
        - DOCKERFILE=Dockerfile_stable
    -
      name: "refs/tags/v1.5.3"
      env:
        - DOCKERFILE=Dockerfile_stable
    -
      name: "refs/tags/v1.5.5"
      env:
        - DOCKERFILE=Dockerfile_stable
    -
      name: "refs/tags/v1.5.6"
      env:
        - DOCKERFILE=Dockerfile_stable
    -
      name: "refs/tags/v1.5.8"
      env:
        - DOCKERFILE=Dockerfile_stable
    -
      name: "refs/tags/v1.6.0"
      env:
        - DOCKERFILE=Dockerfile_stable
    -
      name: "refs/tags/v2.0.0"
      env:
        - DOCKERFILE=Dockerfile_master
    -
      name: "clean aws"
      before_script: skip
      script: skip
      after_script: skip
      after_success:
        - aws s3 rm --recursive s3://iceflower-redeclipse-server-docker/$TRAVIS_BUILD_NUMBER

before_install:
  - mkdir -p ~/aws-cache/
  - aws s3 sync s3://iceflower-redeclipse-server-docker/$TRAVIS_BUILD_NUMBER ~/aws-cache/

install:
  - mkdir -p ~/.docker/
  - bash ./ci/enable-experimental-docker.sh

before_cache:
  - rm ~/.rsd-updater/Dockerfile_master
  - rm ~/.rsd-updater/Dockerfile_stable
  - rm ~/.rsd-updater/.dockerignore
  - rm ~/.rsd-updater/updater

cache:
  directories:
    - ~/.rsd-updater/

before_script:
  - mkdir -p ~/.rsd-updater/
  - cp Dockerfile_stable ~/.rsd-updater/
  - cp Dockerfile_master ~/.rsd-updater/
  - cp .dockerignore ~/.rsd-updater/
  - cp ~/aws-cache/updater ~/.rsd-updater/

script:
  - cd ~/.rsd-updater/
  - ./updater --dockerfile $DOCKERFILE --ref $TRAVIS_JOB_NAME --arch $ARCH --repo $REPO --user $USER --password $DOCKER_PASSWORD ./

after_script:
  - docker logout
