sudo: required

services:
  - docker

env:
  - BRANCH="stable"
  - BRANCH="master"

cache:
  directories:
    - $HOME/devel.sha
    - $HOME/stable.sha

install:
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

before_script:
  - docker login -u=iceflower -p="$DOCKER_PASSWORD"

script:
  - bash scripts/update.sh
