sudo: required

services:
  - docker

install:
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
# build amd64 devel
  - export REPO=iceflower/red-eclipse_devel_server_test
  - docker build --squash -t "$REPO:latest" -f Dockerfile_devel .

after_success:
  - docker login -u=iceflower -p="$DOCKER_PASSWORD"
  - docker push $REPO
