sudo: required

language: cpp

branches:
  only:
  - master
  - experimental

services:
  - docker

matrix:
  include:
  - name: "master"
    env:
      - arch=amd64
      - BRANCH=master
  - name: "stable"
    env:
      - arch=amd64
      - BRANCH=stable

cache:
  directories:
    - ~/.re-docker

install:
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

before_script:
  - echo $DOCKER_PASSWORD | docker login -u=iceflower --password-stdin
  - mkdir -p ~/.re-docker/sha/re/
  - mkdir -p ~/.re-docker/sha/baseImg/
  - mkdir -p ~/.re-docker/sha/dockerfile/
  - mkdir -p ~/.docker/
  - echo "{\"experimental\": \"enabled\"}" >> ~/.docker/config.json

script:
  - bash scripts/update.sh

after_script:
  - docker logout
